### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by chtakyol** [uysalaltas/Face-Recognation-OpenCV-Tkinter-#1]
Cannot found "cv2.cv2" in following line;
`def train_faces():`
    `recognizer = cv2.face.LBPHFaceRecognizer_create()`
    `detector = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')`
    `get_imagePath = [os.path.join(newpath,f) for f in os.listdir(newpath)]`
    `faceSamples = []`
    `ids = []`

**Comment by uysalaltas** [comment]
`pip install opencv-contrib-python`

Write this in command shell.
This should work. For explanation you can visit this title.
[https://stackoverflow.com/questions/44633378/attributeerror-module-cv2-cv2-has-no-attribute-createlbphfacerecognizer](url)
